transition-added-to-sections
hrushikeshrv/mjxgui pull request #31
Opened 2023-09-28 16:47 UTC by sricharanandra

Issue #30  
This issue was raised requesting transition effects between the sections in the homepage to enhance the visual experience.

This adds a transition effect which make jumping between sections via the navbar smoother, by adding a scroll behaviour to the entire page in the style.css file.

2023-09-28 16:50 UTC, hrushikeshrv commented
Hi @sricharanandra, thanks for the PR. Although I'm not sure if this PR will count under Hacktoberfest since it seems too trivial. 

I've left a review comment. Please check 👍🏻

2023-09-28 16:51 UTC, hrushikeshrv requested changes

2023-09-28 16:51 UTC, hrushikeshrv commented on docs/styles.css
> +    scroll-behavior: smooth;
There is an `html` selector at line 87 of this file, please add the scroll behavior there.

2023-09-28 17:40 UTC, sricharanandra commented on docs/styles.css
> +    scroll-behavior: smooth;
I've made the suggested changes in a new commit.

2023-09-29 05:02 UTC, merged

2023-09-29 05:02 UTC, hrushikeshrv commented
Thanks @sricharanandra 👍🏻